on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: 'manual run'
        required: true
        default: 'Testing'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: secret test
        env:
          secrets: ${{ secrets.DEV }}
        run: |
          python3 python.py