on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkou
      - uses: actions/checkout@v4
      - name: secret test
        env:
          secrets: ${{ secrets.DEV }}
        run: |
          python3 python.py